# vector

In [1]:
import numpy as np

In [13]:
# np.array(  )

vec1 = np.array( [ 0., 1., 2., 3., 4. ] )
vec1

array([0., 1., 2., 3., 4.])

In [9]:
# np.arange( start inclusive, stop exclusive, step size )

vec2 = np.arange( 0, 5, 1, dtype=float )
vec2

array([0., 1., 2., 3., 4.])

In [10]:
# np.linspace( start inclusive, stop inclusive, number of elements )

vec3 = np.linspace( 0, 4, 5 )
vec3

array([0., 1., 2., 3., 4.])

In [12]:
# np.zeros( n ) returns a vector filled with n zeros

vec4 = np.zeros( 5 )
vec4

array([0., 0., 0., 0., 0.])

In [15]:
for i in range( 5 ):
    vec4[i] = i

vec4

array([0., 1., 2., 3., 4.])

In [25]:
# np.loadtxt(fname, dtype=<class 'float'>, comments='#', delimiter=None, converters=None, skiprows=0, usecols=None, unpack=False, ndmin=0, encoding='bytes', max_rows=None

vec5 = np.loadtxt( "test_number.txt" , delimiter=':')
vec5

array([[1., 2., 3.],
       [2., 3., 4.],
       [3., 4., 5.]])

In [27]:
v1 = vec1 + vec2
v1

array([0., 2., 4., 6., 8.])

In [29]:
v2 = np.zeros( 5 )

for i in range( 5 ):
    v2[i] = vec1[i] + vec2[i]

v2

array([0., 2., 4., 6., 8.])

In [30]:
vec1 += vec2
vec1

array([0., 2., 4., 6., 8.])

In [32]:
v3 = 2*vec3
v3

array([0., 2., 4., 6., 8.])

In [31]:
v4 = vec4 + 3
v4

array([3., 4., 5., 6., 7.])

In [33]:
# np.sin(): applying a function to a vector, element-by-element

v5 = np.sin(vec5)
v5

array([[ 0.84147098,  0.90929743,  0.14112001],
       [ 0.90929743,  0.14112001, -0.7568025 ],
       [ 0.14112001, -0.7568025 , -0.95892427]])

In [35]:
# v.tolist()

lst = v5.tolist()
lst

[[0.8414709848078965, 0.9092974268256817, 0.1411200080598672],
 [0.9092974268256817, 0.1411200080598672, -0.7568024953079282],
 [0.1411200080598672, -0.7568024953079282, -0.9589242746631385]]

# matrix

In [37]:
d1 = np.linspace( 0, 11, 12 )
d1

array([ 0.,  1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10., 11.])

In [36]:
d2 = np.linspace( 0, 11, 12 )
d2

array([ 0.,  1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10., 11.])

In [38]:
# v.shape(), Reshape the first vector to a 3x4 (row x col) matrix

d1.shape = ( 3, 4 )
d1

array([[ 0.,  1.,  2.,  3.],
       [ 4.,  5.,  6.,  7.],
       [ 8.,  9., 10., 11.]])

In [39]:
# v.reshape(), Generate a matrix VIEW to the second vector

view = d2.reshape( (3,4) )
view

array([[ 0.,  1.,  2.,  3.],
       [ 4.,  5.,  6.,  7.],
       [ 8.,  9., 10., 11.]])

In [40]:
total = d1 + view
total

array([[ 0.,  2.,  4.,  6.],
       [ 8., 10., 12., 14.],
       [16., 18., 20., 22.]])

In [42]:
# Element access: [row,col] for matrix

d1[0,1]

1.0

In [43]:
view[0,1]

1.0

In [45]:
d2[1]


1.0

In [56]:
d1.shape

(3, 4)

In [48]:
d2.shape

(12,)

In [49]:
view.shape

(3, 4)

In [57]:
d1.size

12

In [52]:
len(d2)

12

In [58]:
d1.ndim

2

In [55]:
d2.ndim

1

# slice

In [59]:
# Create a 12 element vector and reshape into 3x4 matrix

d = np.linspace( 0, 11, 12 )
d.shape = ( 3,4 )
d

array([[ 0.,  1.,  2.,  3.],
       [ 4.,  5.,  6.,  7.],
       [ 8.,  9., 10., 11.]])

In [64]:
# Individual element: scalar

d[0,1]

1.0

In [61]:
# First row

d[0,:]

array([0., 1., 2., 3.])

In [63]:
# Second col

d[:,1]

array([1., 5., 9.])

In [66]:
# Sub-vector of shape 1

d[0:2,1]

array([1., 5.])

In [68]:
# Sub-array of shape 1x1

d[0:2,1:2]

array([[1.],
       [5.]])

In [69]:
# Indexing...
# Integer indexing: third and first column

d[ :, [2,0] ]

array([[ 2.,  0.],
       [ 6.,  4.],
       [10.,  8.]])

In [71]:
# Boolean indexing: second and third column

k = np.array( [False, True, True] )

d[ k, : ]

array([[ 4.,  5.,  6.,  7.],
       [ 8.,  9., 10., 11.]])

In [3]:

L = range(1000)
%timeit [i**2 for i in L]

10000 loops, best of 3: 61 µs per loop


In [72]:
b = np.array([[0, 1, 2], [3, 4, 5]]) 
b

array([[0, 1, 2],
       [3, 4, 5]])

In [73]:
c = np.array([[[1], [2]], [[3], [4]]])
c

array([[[1],
        [2]],

       [[3],
        [4]]])

 # inline function

In [74]:
np.ones((3, 3))

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [75]:
np.zeros((2, 2))


array([[0., 0.],
       [0., 0.]])

In [76]:
np.eye(3)


array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [77]:
np.diag(np.array([1, 2, 3, 4]))


array([[1, 0, 0, 0],
       [0, 2, 0, 0],
       [0, 0, 3, 0],
       [0, 0, 0, 4]])

In [78]:
np.random.rand(4)   


array([0.48667279, 0.4054036 , 0.30190387, 0.1514415 ])

In [89]:
# same seed, same random number
# empyt default random
# work only once

np.random.seed(1234)
np.random.random()

0.1915194503788923

In [90]:
np.random.random()

0.6221087710398319

In [92]:
np.array([1, 2, 3], dtype=float)

array([1., 2., 3.])

In [94]:
np.array([1+2j, 3+4j, 5+6*1j])

array([1.+2.j, 3.+4.j, 5.+6.j])

In [95]:
np.array([True, False, False, True])

array([ True, False, False,  True])

In [96]:
np.array(['Bonjour', 'Hello', 'Hallo',])

array(['Bonjour', 'Hello', 'Hallo'], dtype='<U7')